version: "3.5"

services:
    mysql:
        restart: unless-stopped
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: "test-mysql1"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
